Fix PVC for EKS

diff --git a/Jenkins-Pipeline-Code/Jenkinsfile-Frontend b/Jenkins-Pipeline-Code/Jenkinsfile-Frontend
--- a/Jenkins-Pipeline-Code/Jenkinsfile-Frontend
+++ b/Jenkins-Pipeline-Code/Jenkinsfile-Frontend
@@ -5,11 +5,13 @@ pipeline {
         nodejs 'nodejs'
     }
     environment {
+        JAVA_HOME = '/usr/lib/jvm/java-17-openjdk-amd64/bin/java'
+        PATH = "${JAVA_HOME}/bin:${env.PATH}"
         SCANNER_HOME = tool 'sonar-scanner'
         AWS_ACCOUNT_ID = credentials('ACCOUNT_ID')
         AWS_ECR_REPO_NAME = credentials('ECR_REPO1')
         AWS_DEFAULT_REGION = 'us-east-1'
-        REPOSITORY_URI = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/"
+        REPOSITORY_URI = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${AWS_ECR_REPO_NAME}"
     }
     stages {
         stage('Clean Workspace') {
@@ -18,33 +20,40 @@ pipeline {
             }}
         stage('Checkout from GitHub') {
             steps {
-                git credentialsId: 'GITHUB', url: 'https://github.com/AkashHolla/End-to-End-Kubernetes-Three-Tier-DevSecOps-Project.git'
+                git branch:'main', credentialsId: 'GITHUB-APP', url: 'https://github.com/AkashHolla/End-to-End-Kubernetes-Three-Tier-DevSecOps-Project.git'
             }
         }
             stage('SonarQube Analysis'){
                 steps {
                     withSonarQubeEnv('sonar-server') {
-                         sh ''' $SCANNER_HOME/bin/sonar-scanner \
-                        -Dsonar.projectName=three-tier-frontend \
-                        -Dsonar.projectKey=three-tier-frontend '''
+                         sh ''' 
+                         export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
+                         export PATH=$JAVA_HOME/bin:$PATH
+                         
+                         echo "JAVA_HOME=$JAVA_HOME"
+                         which java
+                         java -version
+                         $SCANNER_HOME/bin/sonar-scanner \
+                        -Dsonar.projectName=frontend \
+                        -Dsonar.projectKey=frontend '''
                     }
                 }
             }
             stage('Quality Gate') {
                 steps {
                     script {
-                        waitForQualityGate abortPipeline: true, credentialsId: 'sonar-token'
+                        waitForQualityGate abortPipeline: false, credentialsId: 'sonar-token'
                     }
                 }
             }
-            stage('OwasP Dependency Check') {
-                steps {
-                    dir('Application-Code/frontend') {
-                    dependencyCheck additionalArguments: '--scan ./ --disableYarnAudit --disableNodeAudit', odcInstallation: 'DP-Check'
-                    dependencyCheckPublisher pattern: '**/dependency-check-report.xml'
-                    }
-                }
-            }
+            // stage('OwasP Dependency Check') {
+            //     steps {
+            //         dir('Application-Code/frontend') {
+            //         dependencyCheck additionalArguments: '--scan ./ --disableYarnAudit --disableNodeAudit', odcInstallation: 'DP-Check'
+            //         dependencyCheckPublisher pattern: '**/dependency-check-report.xml'
+            //         }
+            //     }
+            // }
             stage('trivy file scan') {
                 steps {
                     dir('Application-Code/frontend') {
@@ -58,53 +67,85 @@ pipeline {
                         dir('Application-Code/frontend') {
                             sh 'docker system prune -f'
                             sh 'docker container prune -f'
-                            sh 'docker build -t ${AWS_ECR_REPO_NAME}:latest .'
+                            sh 'docker build -t ${AWS_ECR_REPO_NAME}:${BUILD_NUMBER} .'
                     }    }
                 }
             }
             stage('Push to ECR') {
                 steps {
                     script {
-                        sh'aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${REPOSITORY_URI}'
-                        sh'docker tag ${AWS_ECR_REPO_NAME} ${REPOSITORY_URI} ${AWS_ECR_REPO_NAME}:${BUILD_NUMBER}'
-                        sh'docker push ${REPOSITORY_URI} ${AWS_ECR_REPO_NAME}:${BUILD_NUMBER}'
+                       sh '''
+                       set -x   # show commands
+                       set -e   # fail on error
+                        aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | \
+                        docker login --username AWS --password-stdin ${REPOSITORY_URI}
+                
+                        echo "Checking available images..."
+                        docker images
+                
+                        docker tag ${AWS_ECR_REPO_NAME}:${BUILD_NUMBER} ${REPOSITORY_URI}:${BUILD_NUMBER}
+                
+                        docker push ${REPOSITORY_URI}:${BUILD_NUMBER}
+                         '''
                     }
                 }
             }
             stage('trivy image scan') {
                 steps {
-                    sh "trivy image ${REPOSITORY_URI} ${AWS_ECR_REPO_NAME}:${BUILD_NUMBER} > trivyimage.txt"
+                    sh "trivy image ${REPOSITORY_URI}:${BUILD_NUMBER} > trivyimage.txt"
                 }
             }
             stage('checkout code for kubernetes') {
                 steps {
-                    git credentialsId: 'GITHUB', url: 'https://github.com/AkashHolla/End-to-End-Kubernetes-Three-Tier-DevSecOps-Project.git'
+                    git branch: 'main', credentialsId: 'GITHUB-APP', url: 'https://github.com/AkashHolla/End-to-End-Kubernetes-Three-Tier-DevSecOps-Project.git'
                 }
             }
-            stage('update deployment file') {
-                environment{
-                    GIT_REPO_NAME = 'End-to-End-Kubernetes-Three-Tier-DevSecOps-Project'
-                    GIT_USER_NAME = 'AkashHolla'
-                }
+            stage('DEBUG BEFORE UPDATE') {
                 steps {
-                dir('Kubernetes-Manifests-file/Frontend') {
-                    withCredentials([string(credentialsId: 'github', variable: 'GITHUB_TOKEN')]) {
-                        sh '''
-                            git config user.email "akashholla2025@gmail.com"
-                            git config user.name "AkashHolla"
-                            BUILD_NUMBER=${BUILD_NUMBER}
-                            echo $BUILD_NUMBER
-                            imageTag=$(grep -oP '(?<=frontend:)[^ ]+' deployment.yaml)
-                            echo $imageTag
-                            sed -i "s/${AWS_ECR_REPO_NAME}:${imageTag}/${AWS_ECR_REPO_NAME}:${BUILD_NUMBER}/" deployment.yaml
-                            git add deployment.yaml
-                            git commit -m "Update deployment Image to version \${BUILD_NUMBER}"
-                            git push https://${GITHUB_TOKEN}@github.com/${GIT_USER_NAME}/${GIT_REPO_NAME} HEAD:master
-                        '''
-                    }
+                    echo "Reached before update stage"
                 }
             }
-          
-          }
+            stage('Update Deployment File') {
+    environment {
+        GIT_REPO_NAME = 'End-to-End-Kubernetes-Three-Tier-DevSecOps-Project'
+        GIT_USER_NAME = 'AkashHolla'
     }
+    steps {
+        dir('Kubernetes-Manifests-file/Frontend') {
+            withCredentials([usernamePassword(
+                credentialsId: 'GITHUB-APP',
+                usernameVariable: 'GIT_USER',
+                passwordVariable: 'GITHUB_TOKEN'
+            )]) {
+
+                echo "INSIDE CREDENTIALS BLOCK ✅"
+
+                sh '''
+                set -x
+
+                echo "Current directory:"
+                pwd
+                ls -l
+
+                echo "Before update:"
+                cat deployment.yaml
+
+                sed -i "s|image: .*|image: ${REPOSITORY_URI}:${BUILD_NUMBER}|g" deployment.yaml
+
+                echo "After update:"
+                cat deployment.yaml
+
+                git config user.email "akashholla2025@gmail.com"
+                git config user.name "AkashHolla"
+
+                git add deployment.yaml
+                git commit -m "Update deployment Image to version ${BUILD_NUMBER}" || echo "No changes"
+
+                git push https://${GIT_USER}:${GITHUB_TOKEN}@github.com/${GIT_USER_NAME}/${GIT_REPO_NAME} HEAD:main
+                '''
+            }
+        }
+    }
+}
+}
 }
